<?php

namespace Proxies\__CG__\VC\ReservasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ReservaProducto extends \VC\ReservasBundle\Entity\ReservaProducto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombreProducto($nombreProducto)
    {
        $this->__load();
        return parent::setNombreProducto($nombreProducto);
    }

    public function getNombreProducto()
    {
        $this->__load();
        return parent::getNombreProducto();
    }

    public function setPiezas($piezas)
    {
        $this->__load();
        return parent::setPiezas($piezas);
    }

    public function getPiezas()
    {
        $this->__load();
        return parent::getPiezas();
    }

    public function setFbe($fbe)
    {
        $this->__load();
        return parent::setFbe($fbe);
    }

    public function getFbe()
    {
        $this->__load();
        return parent::getFbe();
    }

    public function setReserva(\VC\ReservasBundle\Entity\Reserva $reserva = NULL)
    {
        $this->__load();
        return parent::setReserva($reserva);
    }

    public function getReserva()
    {
        $this->__load();
        return parent::getReserva();
    }

    public function setPeso($peso)
    {
        $this->__load();
        return parent::setPeso($peso);
    }

    public function getPeso()
    {
        $this->__load();
        return parent::getPeso();
    }

    public function setTipoCaja(\VC\ReservasBundle\Entity\TipoCaja $tipoCaja = NULL)
    {
        $this->__load();
        return parent::setTipoCaja($tipoCaja);
    }

    public function getTipoCaja()
    {
        $this->__load();
        return parent::getTipoCaja();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'peso', 'nombreProducto', 'piezas', 'fbe', 'reserva', 'tipoCaja');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}