<?php

namespace Proxies\__CG__\VC\ReservasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Reserva extends \VC\ReservasBundle\Entity\Reserva implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCreacion($creacion)
    {
        $this->__load();
        return parent::setCreacion($creacion);
    }

    public function getCreacion()
    {
        $this->__load();
        return parent::getCreacion();
    }

    public function setFechaServicio($fechaServicio)
    {
        $this->__load();
        return parent::setFechaServicio($fechaServicio);
    }

    public function getFechaServicio()
    {
        $this->__load();
        return parent::getFechaServicio();
    }

    public function setGuiaMaster($guiaMaster)
    {
        $this->__load();
        return parent::setGuiaMaster($guiaMaster);
    }

    public function getGuiaMaster()
    {
        $this->__load();
        return parent::getGuiaMaster();
    }

    public function setHoraServicio($horaServicio)
    {
        $this->__load();
        return parent::setHoraServicio($horaServicio);
    }

    public function getHoraServicio()
    {
        $this->__load();
        return parent::getHoraServicio();
    }

    public function setTemperaturaRequerida($temperaturaRequerida)
    {
        $this->__load();
        return parent::setTemperaturaRequerida($temperaturaRequerida);
    }

    public function getTemperaturaRequerida()
    {
        $this->__load();
        return parent::getTemperaturaRequerida();
    }

    public function setContacto($contacto)
    {
        $this->__load();
        return parent::setContacto($contacto);
    }

    public function getContacto()
    {
        $this->__load();
        return parent::getContacto();
    }

    public function setNotas($notas)
    {
        $this->__load();
        return parent::setNotas($notas);
    }

    public function getNotas()
    {
        $this->__load();
        return parent::getNotas();
    }

    public function setCreadoPor(\VC\UserBundle\Entity\User $creadoPor = NULL)
    {
        $this->__load();
        return parent::setCreadoPor($creadoPor);
    }

    public function getCreadoPor()
    {
        $this->__load();
        return parent::getCreadoPor();
    }

    public function setAgencia(\VC\BaseBundle\Entity\Agencia $agencia = NULL)
    {
        $this->__load();
        return parent::setAgencia($agencia);
    }

    public function getAgencia()
    {
        $this->__load();
        return parent::getAgencia();
    }

    public function setAerolinea(\VC\BaseBundle\Entity\Aerolinea $aerolinea = NULL)
    {
        $this->__load();
        return parent::setAerolinea($aerolinea);
    }

    public function getAerolinea()
    {
        $this->__load();
        return parent::getAerolinea();
    }

    public function setCliente(\VC\BaseBundle\Entity\Cliente $cliente = NULL)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creacion', 'fechaServicio', 'guiaMaster', 'horaServicio', 'temperaturaRequerida', 'contacto', 'notas', 'agencia', 'aerolinea', 'cliente', 'creado_por');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}